services:
  web:
    build: .
    ports:
      - "8888:8888"
  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
       - ./local/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
       - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data: