services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      DB_ADDRESS: "db:3306"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
       - ./local/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
       - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$$MYSQL_ROOT_USER", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s

volumes:
  db_data: