DROP SCHEMA IF EXISTS app;
CREATE DATABASE app;
USE app;

DROP TABLE IF EXISTS singers;
CREATE TABLE singers (
	`id`	INTEGER NOT NULL AUTO_INCREMENT,
	`name`	VARCHAR(255) NOT NULL,
	
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME NULL,
	
	PRIMARY KEY (`id`)
);
